name: SimpleFSplugin
version: '1.0'
main: net.simple.forscore.plugin.Main
api-version: 1.18
authors: [ KessPenGames, AndreyBali ]
description: Плагин для ForScore
website: https://forscore.ru/
softdepend: [ Chatty, DiscordSRV ]
commands:
  fs:
    description: Use /fs [fixadv, cooldown, progress, volcano]
    usage: /fs [fixadv, cooldown, progress, volcano]